model:
  - tabNTL
network:
  - tabNTL
trainer:
  - NTL
device:
  - cuda
batch_size:
  - 128
learning_rate:
  - 0.0005
training_epochs:
  - 100
latent_dim:
  - 32
enc_hdim:
  - 64
enc_nlayers:
  - 5
num_trans:
  - 11
trans_nlayers:
  - 2
trans_hdim:
  - 200
trans_type:
  - residual
loss:
  - DCL
enc_bias:
  - False
batch_norm:
  - True
loss_temp:
  - 0.1
l2:
  - 0.00001
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 100
      gamma: 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 100
      use_train_loss: True

shuffle:
  - True
num_repeat:
  - 3
result_folder:
  - RESULTS/RESULTS_