model:
  - featNTL
trainer:
  - NTL
network:
  - featNTL
device:
  - cuda
batch_size:
  - 500
learning_rate:
  - 0.0004
training_epochs:
  - 30
enc_zdim:
  - 256
enc_nlayers:
  - 1
num_trans:
  - 15
trans_nlayers:
  - 3
trans_hdim:
  - 2048
trans_type:
  - forward
loss:
  - DCL
enc_bias:
  - False
trans_bias:
  - False
batch_norm:
  - False
loss_temp:
  - 0.1
l2:
  - 0.
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 10
      gamma: 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 10
      use_loss: True

shuffle:
  - True

num_repeat:
  - 3
result_folder:
  - RESULTS/RESULTS_