model:
  - visNTL
trainer:
  - NTL
network:
  - visNTL
device:
  - cuda
batch_size:
  - 512
learning_rate:
  - 0.001
training_epochs:
  - 20
enc_hdim:
  - 16
enc_zdim:
  - 64
enc_nlayers:
  - 2
num_trans:
  - 15
trans_nlayers:
  - 1
trans_type:
  - mul
loss:
  - DCL
enc_bias:
  - False
batch_norm:
  - False
loss_temp:
  - 0.1
l2:
  - 0.
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 10
      gamma: 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 10
      use_train_loss: True

shuffle:
  - True

num_repeat:
  - 3
result_folder:
  - RESULTS/RESULTS_